name: Create Pull Request

on:
  pull_request:
    types:
      - closed
    branches: [ develop, master ]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

env:
  REPO_HEAD: ${{ github.base_ref }}
  REPO_BASE: ${{ github.base_ref == 'develop' && 'master' || 'develop' }}

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/workflows/scripts/create-pull-request.js')

            await script({
              github,
              context,
            })
